name: Build Hadoop

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  #   # Publish semver tags as releases.
  #   tags: [ 'v*.*.*' ]
  # pull_request:
  #   branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout Hadoop
        uses: actions/checkout@v4
        with:
          repository: apache/hadoop
          path: hadoop-3.3 # Store in $GITHUB_WORKSPACE/other-repo
          ref: branch-3.3
          
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 8
          distribution: temurin
          
      - name: Install Dependencies
        run: |
          # Maven
          sudo apt-get -y install maven
          # Native libraries
          sudo apt-get -y install build-essential autoconf automake libtool cmake zlib1g-dev pkg-config libssl-dev libsasl2-dev
          # Protocol Buffers 3.7.1 (required to build native code)
          curl -L -s -S https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protobuf-java-3.7.1.tar.gz -o protobuf-3.7.1.tar.gz
          mkdir protobuf-3.7-src
          tar xzf protobuf-3.7.1.tar.gz --strip-components 1 -C protobuf-3.7-src && cd protobuf-3.7-src
          ./configure
          make -j$(nproc)
          sudo make install
          cd ..

      - name: Build Hadoop
        run: |
          cd hadoop-3.3
          mvn package -Pdist -DskipTests -Dtar -Dmaven.javadoc.skip=true

      - name: 'Tar files'
        run: tar -cvf hadoop-3.3.tar -C hadoop-3.3/hadoop-dist/target hadoop-3.3.9-SNAPSHOT

      - name: Upload Hadoop Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: hadoop-3.3
          path: hadoop-3.3.tar


          


          
